<a href="https://colab.research.google.com/github/failure64/ads-optimization/blob/main/Master.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# Data Preprocessing

### Importing dataset and libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [31]:
data_set=pd.read_csv('final dataset.csv')
X =  data_set.iloc[:,:-1].values
Y =  data_set.iloc[:,-1].values

In [32]:
print("X")
print(X)
print("Y")
print(Y)

X
[[0 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 1]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 0]]
Y
[0 0 0 ... 0 0 0]


### Handling Missing Data

In [33]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy ="constant")

imputer.fit(X[:, 0:1]) #all rows but only first column
X[: , 0:1] = imputer.transform(X[:, 0:1])

In [34]:
print("Data after imputation")
print(X)

Data after imputation
[[0 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 1]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 0]]


### Encoding Categorical Data & Feature Scaling

not possible in our case

### Spliting into test amd training data
Standard 70:30 split

In [35]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.3, random_state = 40)

In [38]:
print(len(X))
print(len(X_train))
print(len(X_test))

15000
10500
4500


15000
10500
4500
