<a href="https://colab.research.google.com/github/failure64/ads-optimization/blob/main/Master.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# Data Preprocessing

### Importing dataset and libraries

In [3]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [12]:
data_set=pd.read_csv('final dataset.csv')
X =  data_set.iloc[:,:-1].values
Y =  data_set.iloc[:,-1].values

In [10]:
print("X")
print(X)
print("Y")
print(Y)

X
[[0 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 1]
 [0 0 0 ... 1 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 0]]
Y
[0 0 0 ... 0 0 0]


### Handling Missing Data

In [13]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy = 'mean')

imputer.fit(X[:, 0:1])
X[: , 0:1] = imputer.transform(X[:, 0:1])